name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp-landing-zone

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Decode base64-encoded GCP service account key
      - name: Decode GCP Credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > gcp_credentials.json

      # Initialize Terraform with backend config
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: gcp_credentials.json

      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt -check

      # Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          GOOGLE_CREDENTIALS: gcp_credentials.json
          TF_VAR_project_prefix: ${{ secrets.PROJECT_PREFIX }}
          TF_VAR_org_id: ${{ secrets.ORG_ID }}
          TF_VAR_billing_account_id: ${{ secrets.BILLING_ACCOUNT_ID }}
          TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }}
          TF_VAR_tf_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_log_bucket: ${{ secrets.LOG_BUCKET }}
          TF_VAR_region: us-central1

      # Apply Terraform changes (only on main branch)
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          GOOGLE_CREDENTIALS: gcp_credentials.json
          TF_VAR_project_prefix: ${{ secrets.PROJECT_PREFIX }}
          TF_VAR_org_id: ${{ secrets.ORG_ID }}
          TF_VAR_billing_account_id: ${{ secrets.BILLING_ACCOUNT_ID }}
          TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }}
          TF_VAR_tf_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_log_bucket: ${{ secrets.LOG_BUCKET }}
          TF_VAR_region: us-central1